[package]
name = "rust-fullgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.6.4"
simple_bar = "0.2.2"
