[package]
name = "rust-fullgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
huffman-coding = "0.1.2"
memchr = "2.6.4"
tqdm = "0.6.0"
