[package]
name = "rust-fullgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
bitstream-rs = "0.2.0"
indicatif = "0.17.7"
